//
// The following code is generated by MUDA compiler
//
#include <xmmintrin.h>


 extern void mnoise2 (float * value, const float * x, const float * y) ;

extern void mnoise2_memo (float * value, const float * x, const float * y, float * mxi, float * myi, float * mh00, float * mh10, float * mh01, float * mh11) ;

