//
// The following code is generated by MUDA compiler
//
#include <xmmintrin.h>


 extern void snoise2 (float * value, const float * x, const float * y) ;

extern void snoise2_memo (float * value, const float * x, const float * y, float * mxi, float * myi, float * mmask, float * mh0, float * mh1, float * mh2) ;

