//
// The following code is generated by MUDA compiler
//
#include <immintrin.h>


 extern void isect (const double * rox, const double * roy, const double * roz, const double * rdx, const double * rdy, const double * rdz, const double * v0x, const double * v0y, const double * v0z, const double * e1x, const double * e1y, const double * e1z, const double * e2x, const double * e2y, const double * e2z, double * inoutMask, double * inoutT, double * inoutU, double * inoutV) ;

